### ISSUE TITLE
The words aren't in bold

### ISSUE THREAD

**Issue by lionel563** [donkuri/lapis#27] opened 2024-12-15 12:26 UTC
![image](https://github.com/user-attachments/assets/30f8272c-65bc-44bc-8fa8-f0642810b781)
I've also tried to change the color of the word, but it doesn't seem to work.
Please reply.

**Comment by bewizible** [comment] 2024-12-16 08:45
Ok so that's chinese, I dont know if there's any coloring in chinese, Lapis is originally made for Japanese and with some tweaks works for Chinese too.

**Comment by donkuri** [comment] 2024-12-16 09:09
Lapis is made to support Japanese, and as a result the parsing is done for Japanese. I'm keeping this open for a week to see if anyone has Chinese expertise and could help you out, but Lapis won't support other languages.

**Comment by bewizible** [comment] 2024-12-17 07:51
> If you're talking about coloring though, then yeah I cannot help.

@itokatsu the thing is, we don't even know if Chinese has coloring though, does it?

**Comment by donkuri** [comment] 2024-12-18 15:30
Yes, the issue isn't really Chinese here, it's probably that the fields aren't set properly.

**Comment by bewizible** [comment] 2024-12-19 13:26
@lionel563 Try `{cloze-prefix}<b>{cloze-body}</b>{cloze-suffix}` or manually bolding to see if it works, closing this issue since there's no reply from OP/it's not a lapis issue, clearly

**Closed by bewizible** 2024-12-19 13:26 UTC
